### ISSUE TITLE
PTBR Translation

### ISSUE THREAD

**Issue by augustoshoiti** [FocusPunch/time-to-cook#3]
Translation files for PT-BR.
[GoogleDrive](https://drive.google.com/drive/folders/102qmR5YJDf1glD7XTyj1n2MK1Wm-41OJ)

**Comment by augustoshoiti** [comment]
For some reason the translation is being displayed incorrectly, with accentuation and rendering errors.
![Captura de Tela (160)](https://github.com/FocusPunch/time-to-cook/assets/115376307/cc90204c-dc14-43da-b593-f6413bc48008)

**Comment by FocusPunch** [comment]
Added! Thank you for the translation!
